name: tabibi_2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  dartz: ^0.10.1
  get_it: ^7.6.4
  pretty_dio_logger: ^1.3.1
  font_awesome_flutter: ^10.5.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  retrofit_generator: ^8.0.4
  flutter_secure_storage: ^9.0.0
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.0.9
  curved_navigation_bar: ^1.0.3
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/wilaya/
    - assets/icon/cardiology.png
    - assets/icon/pediatrics.png
    - assets/icon/neurology.png
    - assets/icon/arthritis.png
    - assets/icon/tooth.png
    - assets/icon/skin.png
    - assets/icon/profile0.png
    - assets/icon/profile1.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/font/OpenSans-Light.ttf
          weight: 300
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 700
